package com.masai.controller;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.masai.Entities.Student;
import com.masai.Repository.StudentDao;
import com.masai.exception.StudentException;

@RestController
@RequestMapping("/JpaApp")
public class StudentController {

	@Autowired
	private StudentDao studentDao;
	
	@PostMapping(value = "/saveStudent")
	public Student saveStudent(@RequestBody Student student) {
		
	Student insertedStudent=studentDao.save(student);
	
	//here we passed Studen obj without roll and we get the inserted Student obj with the autogenerated roll.
	return insertedStudent;
	}
	
	@GetMapping("/getStudent/{roll}")
	public Student getStudentByRoll(@PathVariable int roll) throws StudentException {
		
		Optional<Student> opt=studentDao.findById(roll);
		
//		if(opt.isPresent())
//		{
//			return opt.get();
//		}
//		
//		else {
//			throw new StudentException("Student not found");
//		}
		
		return studentDao.findById(roll).orElseThrow(()-> new StudentException("Student not found") );
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
